### ISSUE TITLE
linux启动有bug

### ISSUE THREAD

**Issue by kN6jq** [MUYU212/JNDI-Injection-Memshell#3]
![image](https://github.com/MUYU212/JNDI-Injection-Memshell/assets/27048404/ba6757d6-99d2-4e5a-adde-8a62f4850cf0)
![image](https://github.com/MUYU212/JNDI-Injection-Memshell/assets/27048404/249d0aca-28f8-4ad3-91d6-a9aeff084e66)

下载的class文件0kb

**Comment by MUYU212** [comment]
师傅是什么服务器环境，还有jdk版本，我复现一下试试呢

**Comment by kN6jq** [comment]
![image](https://github.com/MUYU212/JNDI-Injection-Memshell/assets/27048404/6daf1223-e444-47e7-be8a-03365027e6a7)

执行 java -jar JNDI-Injection-Memshell-1.0-SNAPSHOT-all.jar -A 1.1.1.1监听后

![image](https://github.com/MUYU212/JNDI-Injection-Memshell/assets/27048404/d753e30d-358a-4a51-9f53-cd42057df346)

fastjson环境 https://github.com/lemono0/FastJsonParty   lemono0/fastjsonparty:1247-jndi  注入内存马
![image](https://github.com/MUYU212/JNDI-Injection-Memshell/assets/27048404/a33a2c87-bf20-4318-8fac-4da1dc421be4)

![image](https://github.com/MUYU212/JNDI-Injection-Memshell/assets/27048404/f722651b-2b0e-4b8f-9be0-9dd0690d8bbd)

**Comment by MUYU212** [comment]
更新了一下代码和1.1版本的release。师傅可以再试一下，我在我的ubuntu和同版本的openjdk上测试是没问题的了。
